Anna: '1705'
Cave In Rock: '805'
Eddyville: '1405'
Elizabethtown: '905'
Equality: '1605'
Golconda: '1105'
Hicks: '1505'
Leamington: '705'
Renshaw: '1205'
Rosiclare: '1005'
Simpson: '1305'
Vienna: '1805'
